In [ ]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
arr2= np.flip(arr)
print(arr2)

# method 2
rev = arr[: : -1]
print(rev)


[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
# row wise flatten
flat = arr.flatten(order = 'c')
# column wise flatten
cflat = arr.flatten(order='f')
print(cflat)
print(flat)

# method 2
flat2 = np.ravel(arr,'c')
print(flat2)

[1 2 1 2 4 2 3 5 3]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
comp = np.array_equal(arr1,arr2)
print(comp)

# method 2
compare = np.array_equiv(arr1,arr2)
print(compare)

True
True


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
frequency = np.bincount(x).argmax()
print(frequency)

y = np.array([1,1,1,2,3,4,2,4,3,3])
frequ = np.bincount(y)
maxi = max(frequ)
for i in range(len(frequ)):
  if frequ[i] == maxi:
    print(i," ")


1
1  
3  


In [ ]:
import numpy as np
gfg = np.matrix([[4,1,9],[12,3,1],[4,5,6]])
sum = np.sum(gfg)
print(sum)

# 2nd part- row wise sum
rsum = np.sum(gfg,axis=1)
print(rsum)

# 3rd part - column wise sum
csum = np.sum(gfg, axis=0)
print(csum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
from ast import Yield
import numpy as np
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
# sum of diagonals
diagsum = np.trace(n_array)
print(diagsum)

# eigen values and eigen vector
value,vector = np.linalg.eig(n_array)
print(value)
print(vector)

# inverse of matrix
inverse = np.linalg.inv(n_array)
print(inverse)


# determinant of matrix
deter = np.linalg.det(n_array)
print(deter)


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [ ]:
import numpy as np
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
multiply = np.dot(p,q)
print(multiply)
covariance = np.cov(p,q)
print(covariance)
print(end = '\n')

# part 2
x = np.array([[1,2],[2,3],[4,5]])
y = np.array([[4,5,1],[6,7,2]])
mult = np.dot(x,y)
print(mult)
x1 = x.flatten(order = 'c')
y1 = y.flatten(order = 'c')
covar = np.cov(x1,y1)
print(covar)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
import numpy as np
import itertools
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x,y)
print("inner product")
print(inner)
print(end='\n')
outer = np.outer(x,y)
print("outer product")
print(outer)
# cartesian product
flatx = x.flatten()
flaty = y.flatten()
cp = np.array(list(itertools.product(flatx,flaty)))
print("cartesian product")
print(cp)


inner product
[[17 52]
 [13 62]]

outer product
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian product
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
# element wise absolute value
# (a)(i)
absval = np.abs(array)
print("element wise absolute value")
print(absval)

# (a)(ii)
# Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
# row.
flat = array.flatten()
percent= np.percentile(flat,[25,50,75])
print("percentile of array: ")
print(percent)
percentR = np.percentile(array,[25,50,75],axis = 1)
print("percentile for each row: ")
print(percentR)
percentC = np.percentile(array,[25,50,75],axis = 0)
print("percentile for each column: ")
print(percentC)

# (a)(iii)
# Mean, Median and Standard Deviation of flattened array, of each column, and
# each row
meanF = np.mean(flat)
print("mean of flattened array")
print(meanF)
medianF = np.median(flat)
print("median of flattened array")
print(medianF)
stdF = np.std(flat)
print("standard deviation of flattened array")
print(stdF)

# for each row
meanR = np.mean(array, axis=1)
print("row wise mean")
print(meanR)
medianR = np.median(array, axis=1)
print("row wise median")
print(medianR)
stdR = np.std(array, axis=1)
print("row wise std dev")
print(stdR)

# column wise
meanC = np.mean(array, axis=0)
print("column wise mean")
print(meanC)
medianC = np.median(array, axis=0)
print("column wise median")
print(medianC)
stdC = np.std(array, axis=0)
print("column wise std dev")
print(stdC)

element wise absolute value
[[1 2 3]
 [4 5 6]]
percentile of array: 
[-3.5 -0.5  2.5]
percentile for each row: 
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
percentile for each column: 
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
mean of flattened array
-0.5
median of flattened array
-0.5
standard deviation of flattened array
3.8622100754188224
row wise mean
[ 0.66666667 -1.66666667]
row wise median
[ 1. -4.]
row wise std dev
[2.05480467 4.78423336]
column wise mean
[-1.5  1.5 -1.5]
column wise median
[-1.5  1.5 -1.5]
column wise std dev
[2.5 3.5 4.5]


In [ ]:
# For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
# and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
print("floor: ")
print(floor)
ceil = np.ceil(a)
print("ceil: ")
print(ceil)
truncate = np.trunc(a)
print("truncated values: ")
print(truncate)
round = np.round(a)
print("rounded values: ")
print(round)

floor: 
[-2. -2. -1.  0.  1.  1.  3.]
ceil: 
[-1. -1. -0.  1.  2.  2.  3.]
truncated values: 
[-1. -1. -0.  0.  1.  1.  3.]
rounded values: 
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
# (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
# i. Sorted array
array = np.array([10, 52, 62, 16, 16, 54, 453])
sort = np.sort(array)
print("sorted array: ")
print(sort)
# ii. Indices of sorted array
# argsort gives actual indices of the sorted array
indices = np.argsort(array)
print("indices: ")
print(indices)
# iii. 4 smallest elements
smallest4 = np.partition(array,4)[:4]
print("4 smallest elements: ")
smallest = np.sort(smallest4)
print(smallest)
# iv. 5 largest elements
# -5 means peeche se 5elements
largest5 = np.partition(array,-5)[-5:]
print("5 largest elements: ")
largest = np.sort(largest5)
print(largest)

# method 2 using argpartition -> this gives indices of largest elements
lar = np.argpartition(array,-5)[-5:]
print("method 2 find largest: ")
print(array[lar])

sorted array: 
[ 10  16  16  52  54  62 453]
indices: 
[0 3 4 1 5 2 6]
4 smallest elements: 
[10 16 16 52]
5 largest elements: 
[ 16  52  54  62 453]
method 2 find largest: 
[ 16  52  62  54 453]


In [ ]:
# (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
# i. Integer elements only
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
# floor of int values will be equal to integer itself
intELE = array[np.floor(array)==array]
print("integer values: ")
print(intELE)

# ii. Float elements only
floatELE = array[np.floor(array)!=array]
print("float elements : ")
print(floatELE)

integer values: 
[1. 2. 3. 2.]
float elements : 
[1.2 2.2]


In [3]:
# from PIL import Image
# path = "image_to_array.jpg"
# import numpy as np
# def img_to_arr(path):
#   image = Image.open(path)
#   if image.mode == 'L':
#      # grayscale image
#      array = np.array(image)
#      np.savetxt('grayscale_image.txt',array,fmt='%d')
#      print("grayscale image saved to 'grayscale_image.txt'")
#   elif image.mode =='RGB':
#     array = np.array(image)
#     with open('rgb_image.txt','w')as f:
#       for row in array:
#         np.savetxt(f,row,fmt='%d')
#         f.write('\n')
#     print("RGB image saved to 'rgb_image.txt'")
#   else:
#     print("unsupported image mode")



In [6]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)

    if img.mode == 'L':  # Grayscale
        img_array = np.array(img)
        mode = 'L'
    else:  # RGB
        img_array = np.array(img)
        mode = 'RGB'

    file_name = path.split('/')[-1].split('.')[0] + '_array.txt'
    with open(file_name, 'w') as f:
        f.write(f'{mode}\n')
        f.write(f'{img_array.shape}\n')
        np.savetxt(f, img_array.flatten(), fmt='%d')

    print(f'Image array saved to {file_name}')
    return file_name

In [7]:

def load_image_array(file_name):
    with open(file_name, 'r') as f:
        mode = f.readline().strip()
        shape = tuple(map(int, f.readline().strip()[1:-1].split(',')))
        img_array = np.loadtxt(f, dtype=int)

    img_array = img_array.reshape(shape)

    return img_array

In [9]:

file_name = img_to_array('image_to_array.jpg')

img_array = load_image_array(file_name)

import matplotlib.pyplot as plt

if img_array.ndim == 2:  # Grayscale
    plt.imshow(img_array, cmap='gray')
    print('gray')
else:  # RGB
    plt.imshow(img_array)
    print('rgb')
plt.show()


Image array saved to image_to_array_array.txt
rgb
